const e1 =[
    ['DESERT', 'MOUNT_SW', 'DESERT', 'DESERT', 'OASIS'],
    ['DESERT', 'DESERT', 'DESERT', 'BRIDGE_VERT', 'OASIS'],
    ['BRIDGE_VERT', 'DESERT', 'MOUNT_NW', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'OASIS', 'DESERT'],
    ['DESERT', 'DESERT', 'MOUNT_NE', 'DESERT', 'DESERT']
]

const e2 =[
    ['OASIS', 'DESERT', 'BRIDGE_HOR', 'DESERT', 'DESERT'],
    ['DESERT', 'MOUNT_NW', 'DESERT', 'DESERT', 'MOUNT_NW'],
    ['BRIDGE_VERT', 'OASIS', 'MOUNT_NE', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'OASIS', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
]

const e3 =[
    ['DESERT', 'DESERT', 'BRIDGE_HOR', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'BRIDGE_VERT'],
    ['DESERT', 'MOUNT_NW', 'BRIDGE_VERT', 'DESERT', 'DESERT'],
    ['DESERT', 'OASIS', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'BRIDGE_HOR', 'DESERT', 'DESERT', 'MOUNT_NW'],
]

const e4 =[
    ['DESERT', 'DESERT', 'DESERT', 'BRIDGE_HOR', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['BRIDGE_VERT', 'DESERT', 'MOUNT_SW', 'DESERT', 'MOUNT_SW'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'OASIS', 'MOUNT_NE', 'DESERT'],
]

const e5 =[
    ['DESERT', 'DESERT', 'BRIDGE_HOR', 'DESERT', 'DESERT'],
    ['DESERT', 'MOUNT_SE', 'DESERT', 'DESERT', 'DESERT'],
    ['BRIDGE_VERT', 'DESERT', 'DESERT', 'MOUNT_NE', 'DESERT'],
    ['DESERT', 'DESERT', 'BRIDGE_VERT', 'OASIS', 'DESERT'],
    ['DESERT', 'MOUNT_NW', 'DESERT', 'DESERT', 'DESERT'],
]

export const easy = [e1, e2, e3, e3, e5]

const h1 = [
    ['DESERT', 'MOUNT_SW', 'OASIS', 'OASIS', 'DESERT', 'BRIDGE_HOR', 'DESERT'],
    ['BRIDGE_VERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'BRIDGE_VERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'MOUNT_NE', 'DESERT', 'DESERT', 'DESERT'],
    ['MOUNT_NE', 'DESERT', 'MOUNT_SW', 'DESERT', 'BRIDGE_HOR', 'DESERT', 'OASIS'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'BRIDGE_HOR', 'DESERT', 'DESERT', 'DESERT']
]

const h2 = [
    ['DESERT', 'DESERT', 'OASIS', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['BRIDGE_VERT', 'DESERT', 'BRIDGE_HOR', 'DESERT', 'DESERT', 'MOUNT_NW', 'DESERT'],
    ['DESERT', 'DESERT', 'BRIDGE_HOR', 'DESERT', 'DESERT', 'DESERT', 'BRIDGE_VERT'],
    ['MOUNT_SE', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'OASIS', 'DESERT', 'MOUNT_SW', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'MOUNT_SE', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'OASIS', 'DESERT', 'DESERT', 'DESERT', 'DESERT']
]

const h3 = [
    ['DESERT', 'DESERT', 'BRIDGE_HOR', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'BRIDGE_VERT'],
    ['OASIS', 'DESERT', 'MOUNT_NE', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'OASIS', 'MOUNT_NE', 'DESERT', 'BRIDGE_HOR', 'DESERT', 'DESERT'],
    ['BRIDGE_VERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'MOUNT_SW', 'DESERT'],
    ['DESERT', 'DESERT', 'OASIS', 'MOUNT_NE', 'DESERT', 'DESERT', 'DESERT']
]

const h4 = [
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'BRIDGE_VERT', 'DESERT', 'MOUNT_NW', 'DESERT'],
    ['DESERT', 'DESERT', 'MOUNT_NE', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'BRIDGE_HOR', 'DESERT', 'OASIS', 'DESERT', 'BRIDGE_HOR', 'DESERT'],
    ['DESERT', 'DESERT', 'MOUNT_NW', 'DESERT', 'MOUNT_SW', 'DESERT', 'DESERT'],
    ['BRIDGE_VERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'MOUNT_NE', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT']
]

const h5 = [
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'MOUNT_SE', 'DESERT'],
    ['DESERT', 'BRIDGE_HOR', 'BRIDGE_HOR', 'DESERT', 'MOUNT_SW', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'MOUNT_SE', 'DESERT', 'OASIS', 'DESERT', 'DESERT'],
    ['DESERT', 'MOUNT_NW', 'DESERT', 'BRIDGE_VERT', 'DESERT', 'DESERT', 'DESERT'],
    ['DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT', 'DESERT']
]

export const hard = [h1, h2, h3, h4, h5]